# Generated by Django 4.0.4 on 2022-04-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='D_czb',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='D_czvt',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='N_e',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='N_max',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='S_n',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='delta',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f1000',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f140',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f2000',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f250',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f4000',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f500',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f63',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='f8000',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='group',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='pe',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='engine',
            name='pz',
            field=models.FloatField(default='0'),
        ),
    ]
