from django.db import models

class Engine(models.Model):
    name = models.TextField(default='some Engine')
    nu = models.IntegerField(default='0')
    N_e = models.FloatField(default='0')
    pe = models.FloatField(default='0')
    pz = models.FloatField(default='0')
    N_max = models.FloatField(default='0')
    delta = models.FloatField(default='0')
    D_czvt = models.FloatField(default='0')
    D_czb   = models.FloatField(default='0')
    group = models.FloatField(default='0')
    f63 = models.FloatField(default='0')
    f140 = models.FloatField(default='0')
    f250 = models.FloatField(default='0')
    f500 = models.FloatField(default='0')
    f1000 = models.FloatField(default='0')
    f2000 = models.FloatField(default='0')
    f4000 = models.FloatField(default='0')
    f8000 = models.FloatField(default='0')
    S_n = models.FloatField(default='0')